# NOTE: The env groups should be first created in the Render dashboard
# Since they do not allow `sync: false` in env groups, this is seems to be the only way

projects:
  - name: gfed-bff-project
    environments:
      - name: production
        services:
          - type: web
            runtime: image
            plan: standard
            name: gateway-prod
            region: frankfurt
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/gateway:prod-latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: standard
            name: content-prod
            region: frankfurt
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/content:prod-latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: standard
            name: products-prod
            region: frankfurt
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/products:prod-latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: standard
            name: orders-prod
            region: frankfurt
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/orders:prod-latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: standard
            name: customers-prod
            region: frankfurt
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/customers:prod-latest
            envVars:
              - fromGroup: bff-prod-env-group

          - type: keyvalue
            name: redis-prod
            plan: free
            region: frankfurt
            maxmemoryPolicy: allkeys-lru
            ipAllowList: []
      - name: smoke
        services:
          - type: web
            runtime: image
            plan: free
            name: gateway-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/gateway:smoke-latest
            envVars:
              - fromGroup: bff-smoke-env-group
              - key: SUPERGRAPH_SDL_URL
                value: https://api.github.com/repos/goodfrontend/gfed-medusa-schema-registry/contents/supergraph/smoke/latest.graphql
                previewValue: ''

          - type: web
            runtime: image
            plan: free
            name: content-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/content:smoke-latest
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: products-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/products:smoke-latest
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: orders-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/orders:smoke-latest
            envVars:
              - fromGroup: bff-smoke-env-group

          - type: web
            runtime: image
            plan: free
            name: customers-smoke
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/customers:smoke-latest
            envVars:
              - fromGroup: bff-smoke-env-group

      - name: qa
        services:
          - type: web
            runtime: image
            plan: free
            name: gateway-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/gateway:qa-latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: content-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/content:qa-latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: products-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/products:qa-latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: orders-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/orders:qa-latest
            envVars:
              - fromGroup: bff-qa-env-group

          - type: web
            runtime: image
            plan: free
            name: customers-qa
            region: oregon
            autoDeployTrigger: off
            image:
              url: ghcr.io/goodfrontend/gfed-medusa-bff/customers:qa-latest
            envVars:
              - fromGroup: bff-qa-env-group
